import {
  Organization,
  Integration,
  DailyMetricSnapshot,
  AiDiagnosis,
  ActionQueueItem,
  BusinessMemory,
  AuditLog,
  ChatMessage,
  ProfitBreakdown,
  ProductMarginItem,
  InventorySkuItem,
  PurchaseOrderDraft,
  MetaCreativeAuditorItem,
  CreativeFatigueSummary,
  FounderGuardrailRule,
  AbandonedCheckoutItem,
  RecoveryTemplate,
  MessageDeliveryLog,
  AutopilotRule,
  ImpactLedgerSummary,
  SimulatorTarget,
  CreativeStudioScript,
  VipSegmentItem,
} from './types';

export const INITIAL_ORGANIZATION: Organization = {
  id: 'org_aura_skincare',
  name: 'Aura Skincare Co.',
  currency: 'INR',
  timezone: 'Asia/Kolkata',
};

export const INITIAL_INTEGRATIONS: Integration[] = [
  {
    id: 'int_shopify_01',
    organizationId: 'org_aura_skincare',
    provider: 'SHOPIFY',
    accessToken: 'shpat_live_99a81b72c91',
    storeUrl: 'auraskincare.myshopify.com',
    status: 'CONNECTED',
    lastSyncedAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: 'int_meta_01',
    organizationId: 'org_aura_skincare',
    provider: 'META_ADS',
    accessToken: 'EAAXx918237192',
    accountId: 'act_99182381',
    status: 'CONNECTED',
    lastSyncedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: 'int_ga4_01',
    organizationId: 'org_aura_skincare',
    provider: 'GOOGLE_ANALYTICS',
    accessToken: 'ga4_token_882910',
    accountId: 'properties/31829312',
    status: 'CONNECTED',
    lastSyncedAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
  },
  {
    id: 'int_wa_01',
    organizationId: 'org_aura_skincare',
    provider: 'WHATSAPP_CLOUDFLARE',
    accessToken: 'wa_access_881920',
    accountId: '+91 8000 123 456',
    status: 'CONNECTED',
    lastSyncedAt: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
  },
  {
    id: 'int_klaviyo_01',
    organizationId: 'org_aura_skincare',
    provider: 'KLAVIYO',
    accessToken: 'pk_klaviyo_881293',
    status: 'CONNECTED',
    lastSyncedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
];

export const INITIAL_METRICS_HISTORY: DailyMetricSnapshot[] = [
  {
    id: 'snap_t6',
    organizationId: 'org_aura_skincare',
    date: '2026-08-12',
    revenue: 385000,
    ordersCount: 226,
    aov: 1703.54,
    conversionRate: 2.85,
    trafficVisitors: 7930,
    metaSpend: 98000,
    googleSpend: 12000,
    blendedRoas: 3.5,
    abandonedCartValue: 64200,
    abandonedCartCount: 38,
  },
  {
    id: 'snap_t5',
    organizationId: 'org_aura_skincare',
    date: '2026-08-13',
    revenue: 412000,
    ordersCount: 242,
    aov: 1702.48,
    conversionRate: 2.92,
    trafficVisitors: 8287,
    metaSpend: 102000,
    googleSpend: 14000,
    blendedRoas: 3.55,
    abandonedCartValue: 58900,
    abandonedCartCount: 35,
  },
  {
    id: 'snap_t4',
    organizationId: 'org_aura_skincare',
    date: '2026-08-14',
    revenue: 430000,
    ordersCount: 250,
    aov: 1720.0,
    conversionRate: 3.1,
    trafficVisitors: 8064,
    metaSpend: 105000,
    googleSpend: 15000,
    blendedRoas: 3.58,
    abandonedCartValue: 61000,
    abandonedCartCount: 36,
  },
  {
    id: 'snap_t3',
    organizationId: 'org_aura_skincare',
    date: '2026-08-15',
    revenue: 445000,
    ordersCount: 258,
    aov: 1724.8,
    conversionRate: 3.05,
    trafficVisitors: 8459,
    metaSpend: 110000,
    googleSpend: 15000,
    blendedRoas: 3.56,
    abandonedCartValue: 72000,
    abandonedCartCount: 41,
  },
  {
    id: 'snap_t2',
    organizationId: 'org_aura_skincare',
    date: '2026-08-16',
    revenue: 420000,
    ordersCount: 240,
    aov: 1750.0,
    conversionRate: 2.88,
    trafficVisitors: 8333,
    metaSpend: 112000,
    googleSpend: 16000,
    blendedRoas: 3.28,
    abandonedCartValue: 68500,
    abandonedCartCount: 39,
  },
  {
    id: 'snap_t1',
    organizationId: 'org_aura_skincare',
    date: '2026-08-17',
    revenue: 399500,
    ordersCount: 232,
    aov: 1721.98,
    conversionRate: 2.74,
    trafficVisitors: 8467,
    metaSpend: 115000,
    googleSpend: 15000,
    blendedRoas: 3.07,
    abandonedCartValue: 79000,
    abandonedCartCount: 44,
  },
  {
    id: 'snap_t0',
    organizationId: 'org_aura_skincare',
    date: '2026-08-18',
    revenue: 342800,
    ordersCount: 198,
    aov: 1731.31,
    conversionRate: 2.38,
    trafficVisitors: 8319,
    metaSpend: 115000,
    googleSpend: 15000,
    blendedRoas: 2.64,
    abandonedCartValue: 88400,
    abandonedCartCount: 42,
  },
];

export const INITIAL_DIAGNOSIS: AiDiagnosis = {
  id: 'diag_2026_08_18',
  organizationId: 'org_aura_skincare',
  date: '2026-08-18',
  urgency: 'HIGH',
  confidenceScore: 0.94,
  headline: 'Revenue dropped 14.2% due to Meta creative fatigue and checkout abandonment',
  summary:
    'Yesterday net sales declined by ₹56,700 compared to the previous day. Meta adset "Summer_Set_B" suffered severe creative fatigue with frequency reaching 6.2x, causing ad return on that set to crash from 3.47x to 0.90x. Simultaneously, 42 high-intent checkouts dropped off at payment.',
  rootCauses: [
    {
      metric: 'Adset Summer_Set_B Fatigue',
      impact: '-₹24,000 net profit loss',
      description: 'Ad frequency crossed 6.2x. CPM rose 48% with 0 purchases on ₹24,000 spend.',
      affectedItem: 'Meta Adset: Summer_Set_B',
    },
    {
      metric: 'Checkout Abandonment Surge',
      impact: '₹88,400 unrecovered revenue',
      description: '42 cart drops at final payment screen.',
      affectedItem: 'Shopify Checkout Drop-off',
    },
    {
      metric: 'Radiance Serum Stockout Threat',
      impact: '6.5 Days of Supply Left',
      description: 'Top revenue driver is burning stock 2.1x faster than lead time.',
      affectedItem: 'SKU: AUR-SER-001',
    },
  ],
  createdAt: '2026-08-19T06:00:00Z',
};

export const INITIAL_ACTION_QUEUE: ActionQueueItem[] = [
  {
    id: 'act_meta_pause_reallocate',
    organizationId: 'org_aura_skincare',
    title: 'Pause Fatigued Adset "Summer_Set_B" & Boost Winning Campaign by 15%',
    description: 'Stop burning budget on high-frequency adset (ROAS 0.9x) and shift ₹5,000/day into winning broad campaign (ROAS 4.1x).',
    category: 'META_ADS',
    impactEstimateMin: 35000,
    impactEstimateMax: 52000,
    status: 'PENDING_APPROVAL',
    payload: {
      campaignIdToPause: 'cmp_104',
      adSetIdToPause: 'adset_summer_B',
      campaignIdToBoost: 'cmp_88',
      boostPercentage: 15,
      newDailyBudget: 57500,
      potentialRevenue: 45000,
    },
    createdAt: '2026-08-18T06:05:00Z',
  },
  {
    id: 'act_wa_cart_recovery',
    organizationId: 'org_aura_skincare',
    title: 'Trigger WhatsApp Abandoned Cart Recovery (42 Checkout Drops)',
    description: 'Send personalized WhatsApp sequence with dynamic 10% discount voucher expiring in 24 hours to 42 abandoned buyers.',
    category: 'CART_RECOVERY',
    impactEstimateMin: 65000,
    impactEstimateMax: 88400,
    status: 'PENDING_APPROVAL',
    payload: {
      targetCount: 42,
      discountCode: 'RECOVER10',
      discountPercent: 10,
      expiryHours: 24,
      potentialRevenue: 88400,
    },
    createdAt: '2026-08-18T06:06:00Z',
  },
  {
    id: 'act_vip_winback_blast',
    organizationId: 'org_aura_skincare',
    title: 'Deploy VIP Winback Voucher to 318 Dormant Customers',
    description: 'Broadcast personalized WhatsApp & Email reminder with exclusive VIP 15% voucher to customers inactive for 60+ days.',
    category: 'WINBACK_EMAIL',
    impactEstimateMin: 48000,
    impactEstimateMax: 72000,
    status: 'PENDING_APPROVAL',
    payload: {
      customerSegment: 'VIP_DORMANT_60D',
      targetCount: 318,
      discountCode: 'WELCOMEBACK15',
      discountPercent: 15,
      expiryHours: 72,
      potentialRevenue: 62000,
    },
    createdAt: '2026-08-18T06:07:00Z',
  },
];

// -------------------------------------------------------------
// OPERATOR AI v4.0 NEW CORE DATASETS
// -------------------------------------------------------------

// 1. Autopilot Switchboard Rules
export const INITIAL_AUTOPILOT_RULES: AutopilotRule[] = [
  {
    id: 'auto_cart_recovery',
    title: 'Abandoned Cart WhatsApp Recovery',
    description: 'Automatically send personalized 10% voucher on WhatsApp 45 minutes post-abandonment if cart value > ₹1,500.',
    category: 'CART_RECOVERY',
    conditionSummary: 'Cart > ₹1,500 • 45 min delay • 10% Off Voucher',
    mode: 'FULL_AUTOPILOT',
    timesFired: 128,
    lastFiredAt: '2026-08-19T09:30:00Z',
    impactCreatedTotal: 94600,
    iconName: 'MessageSquare',
  },
  {
    id: 'auto_ad_fatigue_brake',
    title: 'Ad Fatigue Emergency Brake',
    description: 'Automatically pause any adset if ROAS drops below 1.0x with >₹5,000 spend over 48 hours to eliminate ad waste.',
    category: 'AD_FATIGUE',
    conditionSummary: 'ROAS < 1.0x • Spend > ₹5,000 (48h window)',
    mode: 'CO_PILOT',
    timesFired: 14,
    lastFiredAt: '2026-08-18T14:15:00Z',
    impactCreatedTotal: 48200,
    iconName: 'Target',
  },
  {
    id: 'auto_stockout_throttle',
    title: 'Stockout Ad Spend Throttling',
    description: 'Automatically reduce daily Meta ad spend by 30% when inventory drops below 7 days of supply to prevent stockouts.',
    category: 'STOCKOUT_THROTTLE',
    conditionSummary: 'Days of Stock < 7 Days • Throttle Ads -30%',
    mode: 'CO_PILOT',
    timesFired: 6,
    lastFiredAt: '2026-08-17T11:00:00Z',
    impactCreatedTotal: 32000,
    iconName: 'Package',
  },
  {
    id: 'auto_vip_winback',
    title: 'VIP Lapsed Customer Winback',
    description: 'Automatically deliver replenishment discount vouchers to VIP customers dormant for 60+ days.',
    category: 'VIP_WINBACK',
    conditionSummary: 'Dormant > 60 Days • Previous Spend > ₹3,000',
    mode: 'OFF',
    timesFired: 0,
    impactCreatedTotal: 0,
    iconName: 'Sparkles',
  },
];

// 2. Verified ROI Impact Ledger Summary & Actions
export const INITIAL_IMPACT_LEDGER: ImpactLedgerSummary = {
  totalNetValueCreated: 142800,
  wastedAdSpendPrevented: 48200,
  revenueRecovered: 94600,
  items: [
    {
      id: 'imp_01',
      title: 'Paused Fatigued Adset "Summer_Set_B"',
      category: 'AD_SPEND_SAVED',
      amount: 18400,
      actionTaken: 'Halted ad spend burning at 0.9x ROAS with 6.2x frequency.',
      executedAt: '2026-08-18T08:12:00Z',
      status: 'VERIFIED',
    },
    {
      id: 'imp_02',
      title: 'Recovered 14 WhatsApp Carts',
      category: 'REVENUE_RECOVERED',
      amount: 30772,
      actionTaken: 'Delivered personalized dynamic 10% voucher code RECOVER10.',
      executedAt: '2026-08-17T16:30:00Z',
      status: 'VERIFIED',
    },
    {
      id: 'imp_03',
      title: 'Prevented Stockout Backorders on Glow Serum',
      category: 'BACKORDER_PREVENTED',
      amount: 24500,
      actionTaken: 'Throttled linked Meta ad spend by 25% to stretch stock until delivery.',
      executedAt: '2026-08-16T12:00:00Z',
      status: 'VERIFIED',
    },
    {
      id: 'imp_04',
      title: 'Reallocated Budget to Top Winning Ad',
      category: 'PROFIT_EXPANDED',
      amount: 38200,
      actionTaken: 'Boosted winning dermatologist review campaign (4.1x ROAS).',
      executedAt: '2026-08-15T10:00:00Z',
      status: 'VERIFIED',
    },
    {
      id: 'imp_05',
      title: 'VIP Winback Broadcast Conversion (46 orders)',
      category: 'REVENUE_RECOVERED',
      amount: 30928,
      actionTaken: 'Sent exclusive replenishment reminder to dormant 60-day buyers.',
      executedAt: '2026-08-14T14:20:00Z',
      status: 'VERIFIED',
    },
  ],
};

// 3. Simulator Target Defaults
export const INITIAL_SIMULATOR_TARGET: SimulatorTarget = {
  dailyAdSpend: 115000,
  targetRoas: 3.2,
  aov: 1750,
  cogsPercent: 23,
  projectedMonthlyRevenue: 11040000,
  projectedMonthlyProfit: 3422400,
  projectedNetMarginPercent: 31.0,
  breakevenCac: 1207.5,
  stockoutWarningSkus: ['AUR-SER-001'],
  savedAt: '2026-08-19T06:00:00Z',
};

// 4. AI Creative Studio Scripts
export const INITIAL_CREATIVE_SCRIPTS: Record<string, CreativeStudioScript> = {
  cr_fatigued_01: {
    id: 'script_fatigued_01',
    creativeId: 'cr_fatigued_01',
    creativeName: 'Founder Story: Why We Made Aura Serum',
    targetAudience: 'Women 22-45 interested in clean beauty & skincare',
    metaHeadline: 'Dermatologists Call This The #1 Vitamin C Breakthrough',
    primaryAdCopy:
      'Tired of Vitamin C serums that oxidize and turn yellow in 2 weeks? Aura\'s patented triple-stabilized formula delivers 24-hour glow without irritation. Over 12,000 5-star reviews.',
    hooks: [
      {
        id: 'hook_01',
        angleType: 'PROBLEM_AGITATION',
        title: 'The "3 PM Dull Skin" Problem',
        openingLine: '"If your skin starts looking tired and dull by 3 PM no matter how much moisturizer you apply, stop..."',
        explanation: 'Agitates a daily frustration that 80%+ of skincare buyers instantly identify with.',
      },
      {
        id: 'hook_02',
        angleType: 'SOCIAL_PROOF_REVIEW',
        title: 'The 12,000 Switchers Angle',
        openingLine: '"The exact ₹1,499 serum that 12,000 people switched to after tossing out their ₹4,000 imported bottles..."',
        explanation: 'Leverages price-to-value comparison and massive social validation.',
      },
      {
        id: 'hook_03',
        angleType: 'BEHIND_THE_SCENES',
        title: 'The 8-Month Lab Secret',
        openingLine: '"Why our lab spent 8 months testing 47 different formulations before we allowed a single bottle to ship..."',
        explanation: 'Builds immense authority and founder craftsmanship trust.',
      },
    ],
    script: {
      visualCue0to3s: 'Extreme close-up of dull skin under harsh bathroom light, transitioning to immediate glowing dropper application.',
      coreDemo3to15s: 'Split-screen comparison showing typical oxidized yellow serum vs. Aura crystal-clear stabilized serum absorbing into skin in 5 seconds.',
      callToAction15to20s: 'Founder holding bottle: "Tap below to get your bottle with our 30-day empty-bottle money-back guarantee."',
    },
  },
};

// 5. WhatsApp VIP Retention Segments
export const INITIAL_VIP_SEGMENTS: VipSegmentItem[] = [
  {
    id: 'seg_lapsed_vip',
    name: 'Lapsed VIP Customers (60+ Days Inactive)',
    description: 'High-value customers who spent >₹3,000 but haven\'t purchased in the last 60 days.',
    customerCount: 318,
    averageLtv: 4850,
    recommendedDiscount: 15,
    expiryHours: 48,
    potentialRevenue: 78500,
    defaultMessage: 'Hey {{first_name}}! ✨ We noticed it\'s been a while since your last Aura order. Here\'s an exclusive 15% VIP code {{discount_code}} reserved for you, valid for 48 hours!',
  },
  {
    id: 'seg_serum_repeat',
    name: 'Repeat Serum Buyers (Replenishment Due)',
    description: 'Bought Radiance Serum 35-45 days ago and are running low on their bottle.',
    customerCount: 142,
    averageLtv: 3400,
    recommendedDiscount: 10,
    expiryHours: 72,
    potentialRevenue: 42600,
    defaultMessage: 'Hey {{first_name}}! 🌿 Your Radiance Serum is likely running low right about now. Restock today with 10% off using code {{discount_code}} before stock runs out!',
  },
];

// 6. Profit Breakdown & Margin Items
export const INITIAL_PROFIT_BREAKDOWN: ProfitBreakdown = {
  grossRevenue: 342800,
  adSpendTotal: 115000,
  metaSpend: 100000,
  googleSpend: 15000,
  cogsTotal: 78844,
  shippingFulfillmentTotal: 25680,
  gatewayFeesTotal: 6856,
  returnsRefundsTotal: 10284,
  netOperatingProfit: 106136,
  netMarginPercentage: 30.96,
  blendedRoas: 2.98,
  totalOrders: 198,
  aov: 1731.31,
  gatewayFeeRate: 0.02,
};

export const INITIAL_PRODUCT_MARGINS: ProductMarginItem[] = [
  {
    id: 'pm_01',
    sku: 'AUR-SER-001',
    title: 'Radiance Glow Vitamin C Serum (30ml)',
    category: 'Serums',
    sellingPrice: 1499,
    cogsPerUnit: 280,
    cogsTotal: 26880,
    unitsSold: 96,
    grossRevenue: 143904,
    allocatedAdSpend: 39600,
    shippingPerUnit: 120,
    paymentGatewayFee: 2878,
    netContributionProfit: 69606,
    marginPercentage: 48.37,
    roas: 3.63,
    status: 'SCALE_AGGRESSIVELY',
    aiRecommendation: 'High profit hero. Increase dedicated ad budget by +25%.',
  },
  {
    id: 'pm_02',
    sku: 'AUR-MOIST-002',
    title: 'Barrier Repair Ceramide Moisturizer (50ml)',
    category: 'Moisturizers',
    sellingPrice: 1299,
    cogsPerUnit: 240,
    cogsTotal: 12480,
    unitsSold: 52,
    grossRevenue: 67548,
    allocatedAdSpend: 18200,
    shippingPerUnit: 120,
    paymentGatewayFee: 1350,
    netContributionProfit: 29278,
    marginPercentage: 43.34,
    roas: 3.71,
    status: 'SCALE_AGGRESSIVELY',
    aiRecommendation: 'High-margin staple. Top bundle candidate with Serum.',
  },
  {
    id: 'pm_03',
    sku: 'AUR-SUN-003',
    title: 'Ultra-Light Matte Sunscreen SPF 50 (50ml)',
    category: 'Sun Care',
    sellingPrice: 899,
    cogsPerUnit: 310,
    cogsTotal: 9920,
    unitsSold: 32,
    grossRevenue: 28768,
    allocatedAdSpend: 12800,
    shippingPerUnit: 120,
    paymentGatewayFee: 575,
    netContributionProfit: 2473,
    marginPercentage: 8.6,
    roas: 2.25,
    status: 'MARGIN_SQUEEZE',
    aiRecommendation: 'Packaging costs squeezing margin. Raise price to ₹999.',
  },
  {
    id: 'pm_04',
    sku: 'AUR-CLN-004',
    title: 'Centella Gentle Gel Cleanser (150ml)',
    category: 'Cleansers',
    sellingPrice: 699,
    cogsPerUnit: 190,
    cogsTotal: 2280,
    unitsSold: 12,
    grossRevenue: 8388,
    allocatedAdSpend: 9600,
    shippingPerUnit: 120,
    paymentGatewayFee: 167,
    netContributionProfit: -3703,
    marginPercentage: -44.14,
    roas: 0.87,
    status: 'LOSS_LEADER_ALERT',
    aiRecommendation: 'Losing money on ads. Stop standalone ads; use as cart upsell.',
  },
  {
    id: 'pm_05',
    sku: 'AUR-MASK-005',
    title: 'Pink Clay Detoxifying Face Mask (80g)',
    category: 'Masks',
    sellingPrice: 1199,
    cogsPerUnit: 210,
    cogsTotal: 840,
    unitsSold: 4,
    grossRevenue: 4796,
    allocatedAdSpend: 1800,
    shippingPerUnit: 120,
    paymentGatewayFee: 95,
    netContributionProfit: 1581,
    marginPercentage: 32.96,
    roas: 2.66,
    status: 'STEADY_PERFORMER',
    aiRecommendation: 'Low velocity inventory. Bundle with Serum at 20% off.',
  },
  {
    id: 'pm_06',
    sku: 'AUR-TON-006',
    title: 'Niacinamide Pore-Tightening Toner (120ml)',
    category: 'Toners',
    sellingPrice: 999,
    cogsPerUnit: 180,
    cogsTotal: 360,
    unitsSold: 2,
    grossRevenue: 1998,
    allocatedAdSpend: 600,
    shippingPerUnit: 120,
    paymentGatewayFee: 40,
    netContributionProfit: 758,
    marginPercentage: 37.94,
    roas: 3.33,
    status: 'STEADY_PERFORMER',
    aiRecommendation: 'Healthy unit economics. Needs creator UGC assets.',
  },
];

// 7. Inventory SKUs
export const INITIAL_INVENTORY_SKUS: InventorySkuItem[] = [
  {
    id: 'sku_ser_01',
    sku: 'AUR-SER-001',
    title: 'Radiance Glow Vitamin C Serum (30ml)',
    category: 'Serums',
    currentStock: 624,
    dailyVelocity7d: 96,
    dailyVelocity30d: 88,
    dosr: 6.5,
    leadTimeDays: 14,
    reorderPointUnits: 1500,
    unitCost: 280,
    sellingPrice: 1499,
    supplierName: 'Aura Biotech Labs (Mumbai)',
    supplierEmail: 'orders@aurabiotech.in',
    riskLevel: 'CRITICAL_STOCKOUT',
    suggestedActionType: 'AUTO_PO',
    suggestedActionDetails: 'Critical: 6.5 Days left vs 14-day lead time. Reorder 2,500 units immediately.',
  },
  {
    id: 'sku_moist_02',
    sku: 'AUR-MOIST-002',
    title: 'Barrier Repair Ceramide Moisturizer (50ml)',
    category: 'Moisturizers',
    currentStock: 890,
    dailyVelocity7d: 52,
    dailyVelocity30d: 48,
    dosr: 17.1,
    leadTimeDays: 10,
    reorderPointUnits: 600,
    unitCost: 240,
    sellingPrice: 1299,
    supplierName: 'Apex Cosmetics Co. (Ahmedabad)',
    supplierEmail: 'supply@apexcosmetics.com',
    riskLevel: 'LOW_STOCK',
    suggestedActionType: 'AUTO_PO',
    suggestedActionDetails: '17 Days of supply remaining. Standard reorder scheduled in 5 days.',
  },
  {
    id: 'sku_sun_03',
    sku: 'AUR-SUN-003',
    title: 'Ultra-Light Matte Sunscreen SPF 50 (50ml)',
    category: 'Sun Care',
    currentStock: 1450,
    dailyVelocity7d: 32,
    dailyVelocity30d: 35,
    dosr: 45.3,
    leadTimeDays: 12,
    reorderPointUnits: 500,
    unitCost: 310,
    sellingPrice: 899,
    supplierName: 'DermaShield Formulations (Delhi)',
    supplierEmail: 'dispatch@dermashield.in',
    riskLevel: 'HEALTHY',
    suggestedActionType: undefined,
    suggestedActionDetails: 'Stock level optimal for next 45 days.',
  },
  {
    id: 'sku_cln_04',
    sku: 'AUR-CLN-004',
    title: 'Centella Gentle Gel Cleanser (150ml)',
    category: 'Cleansers',
    currentStock: 5200,
    dailyVelocity7d: 12,
    dailyVelocity30d: 10,
    dosr: 433.3,
    leadTimeDays: 14,
    reorderPointUnits: 200,
    unitCost: 190,
    sellingPrice: 699,
    supplierName: 'Aura Biotech Labs (Mumbai)',
    supplierEmail: 'orders@aurabiotech.in',
    riskLevel: 'DEAD_STOCK',
    suggestedActionType: 'BUNDLE_CLEARANCE',
    suggestedActionDetails: '₹9.88L tied up in slow inventory (433 days). Bundle with best-sellers.',
  },
  {
    id: 'sku_mask_05',
    sku: 'AUR-MASK-005',
    title: 'Pink Clay Detoxifying Face Mask (80g)',
    category: 'Masks',
    currentStock: 2400,
    dailyVelocity7d: 4,
    dailyVelocity30d: 5,
    dosr: 600.0,
    leadTimeDays: 20,
    reorderPointUnits: 150,
    unitCost: 210,
    sellingPrice: 1199,
    supplierName: 'Apex Cosmetics Co. (Ahmedabad)',
    supplierEmail: 'supply@apexcosmetics.com',
    riskLevel: 'DEAD_STOCK',
    suggestedActionType: 'FLASH_SALE',
    suggestedActionDetails: 'Over 600 days of stock. Trigger 48-hour 25% off flash sale.',
  },
  {
    id: 'sku_ton_06',
    sku: 'AUR-TON-006',
    title: 'Niacinamide Pore-Tightening Toner (120ml)',
    category: 'Toners',
    currentStock: 480,
    dailyVelocity7d: 18,
    dailyVelocity30d: 16,
    dosr: 26.6,
    leadTimeDays: 10,
    reorderPointUnits: 250,
    unitCost: 180,
    sellingPrice: 999,
    supplierName: 'DermaShield Formulations (Delhi)',
    supplierEmail: 'dispatch@dermashield.in',
    riskLevel: 'HEALTHY',
    suggestedActionType: undefined,
    suggestedActionDetails: 'Healthy inventory runway.',
  },
];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrderDraft[] = [
  {
    id: 'po_1092',
    skuId: 'sku_ser_01',
    skuTitle: 'Radiance Glow Vitamin C Serum (30ml)',
    supplierName: 'Aura Biotech Labs (Mumbai)',
    unitsOrdered: 2500,
    unitCost: 280,
    totalAmount: 700000,
    leadTimeDays: 14,
    status: 'SENT_TO_SUPPLIER',
    poNumber: 'PO-2026-0881',
    createdAt: '2026-08-18T10:30:00Z',
    expectedDeliveryDate: '2026-09-01',
  },
];

// 8. Meta Creatives
export const INITIAL_META_CREATIVES: MetaCreativeAuditorItem[] = [
  {
    id: 'cr_winner_01',
    name: 'UGC: Dermatologist Glow Routine v2',
    campaignName: 'Scale_Broad_Winning_Q3',
    adSetName: 'Broad_Women_25_45',
    format: 'VIDEO_REEL',
    thumbnailUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80',
    spend7d: 48000,
    roas: 4.1,
    hookRate: 44.2,
    holdRate: 18.6,
    firstTimeImpressionRatio: 78.4,
    frequency: 2.1,
    cpc: 14.2,
    ctr: 2.85,
    fatigueStatus: 'SCALING_WINNER',
    aiDiagnosis: 'Top winning creative. High 3s attention (44.2%) and high fresh reach (78.4%). Scale spend safely.',
  },
  {
    id: 'cr_fatigued_01',
    name: 'Founder Story: Why We Made Aura Serum',
    campaignName: 'Retargeting_Summer_Sale',
    adSetName: 'Summer_Set_B',
    format: 'VIDEO_REEL',
    thumbnailUrl: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&auto=format&fit=crop&q=80',
    spend7d: 42000,
    roas: 0.9,
    hookRate: 14.8,
    holdRate: 5.2,
    firstTimeImpressionRatio: 31.0,
    frequency: 6.2,
    cpc: 38.5,
    ctr: 0.82,
    fatigueStatus: 'FATIGUED',
    aiDiagnosis: 'Severe ad fatigue. Frequency 6.2x indicates audience is exhausted of this video. Pause immediately.',
  },
  {
    id: 'cr_early_01',
    name: 'Split Screen: 7 Days Glow Results',
    campaignName: 'Scale_Broad_Winning_Q3',
    adSetName: 'Interests_Clean_Beauty',
    format: 'VIDEO_REEL',
    thumbnailUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&auto=format&fit=crop&q=80',
    spend7d: 25000,
    roas: 2.6,
    hookRate: 26.5,
    holdRate: 11.4,
    firstTimeImpressionRatio: 48.2,
    frequency: 4.1,
    cpc: 22.0,
    ctr: 1.65,
    fatigueStatus: 'EARLY_FATIGUE',
    aiDiagnosis: 'Showing initial fatigue signals. Frequency rising. Prepare fresh video hooks.',
  },
];

export const INITIAL_CREATIVE_SUMMARY: CreativeFatigueSummary = {
  totalActiveCreatives: 3,
  fatiguedCreativesCount: 1,
  scalingWinnersCount: 1,
  dailyRevenueLeaked: 24000,
};

// 9. Playbook Guardrails
export const INITIAL_GUARDRAIL_RULES: FounderGuardrailRule[] = [
  {
    id: 'rule_01',
    title: 'Weekend Ad Spend Surge Cap',
    condition: 'Never increase daily ad spend by >15% on Saturday or Sunday without manual confirmation.',
    category: 'BUDGET_SCALING',
    actionPolicy: 'BLOCK_ACTION',
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'rule_02',
    title: 'Minimum 18% Net Profit Margin Safeguard',
    condition: 'Block automated budget increases if real take-home net margin drops below 18%.',
    category: 'PRICING_MARGINS',
    actionPolicy: 'BLOCK_ACTION',
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'rule_03',
    title: 'Adset Frequency Auto-Throttling',
    condition: 'Flag and pause ad sets if 7-day frequency exceeds 5.0x with ROAS below 1.5x.',
    category: 'CREATIVE_FATIGUE',
    actionPolicy: 'REQUIRE_MANUAL_PIN',
    isActive: true,
    createdAt: '2026-08-05T00:00:00Z',
  },
  {
    id: 'rule_04',
    title: 'Stockout Advertising Brake',
    condition: 'Automatically pause dedicated ad sets if SKU has less than 10 days of inventory left.',
    category: 'INVENTORY_STOCKOUT',
    actionPolicy: 'REQUIRE_MANUAL_PIN',
    isActive: true,
    createdAt: '2026-08-10T00:00:00Z',
  },
];

// 10. Abandoned Checkouts
export const INITIAL_ABANDONED_CHECKOUTS: AbandonedCheckoutItem[] = [
  {
    id: 'chk_1001',
    customerName: 'Priya Sharma',
    customerPhone: '+91 98201 44521',
    customerEmail: 'priya.sharma@gmail.com',
    cartTotal: 2798,
    cartItems: [
      { id: 'item_1', name: 'Radiance Glow Serum (30ml)', price: 1499, quantity: 1, sku: 'AUR-SER-001' },
      { id: 'item_2', name: 'Ceramide Moisturizer (50ml)', price: 1299, quantity: 1, sku: 'AUR-MOIST-002' },
    ],
    abandonedMinutesAgo: 45,
    dropoffStep: 'PAYMENT_STEP',
    status: 'PENDING',
    assignedDiscountCode: 'RECOVER10',
  },
  {
    id: 'chk_1002',
    customerName: 'Ananya Deshmukh',
    customerPhone: '+91 98450 11289',
    customerEmail: 'ananya.d@outlook.com',
    cartTotal: 1499,
    cartItems: [
      { id: 'item_3', name: 'Radiance Glow Serum (30ml)', price: 1499, quantity: 1, sku: 'AUR-SER-001' },
    ],
    abandonedMinutesAgo: 82,
    dropoffStep: 'PAYMENT_STEP',
    status: 'PENDING',
    assignedDiscountCode: 'RECOVER10',
  },
  {
    id: 'chk_1003',
    customerName: 'Rohan Mehta',
    customerPhone: '+91 97112 88412',
    customerEmail: 'rohan.mehta@gmail.com',
    cartTotal: 3497,
    cartItems: [
      { id: 'item_4', name: 'Radiance Glow Serum (30ml)', price: 1499, quantity: 1, sku: 'AUR-SER-001' },
      { id: 'item_5', name: 'Ceramide Moisturizer (50ml)', price: 1299, quantity: 1, sku: 'AUR-MOIST-002' },
      { id: 'item_6', name: 'Gentle Gel Cleanser (150ml)', price: 699, quantity: 1, sku: 'AUR-CLN-004' },
    ],
    abandonedMinutesAgo: 110,
    dropoffStep: 'SHIPPING_STEP',
    status: 'PENDING',
    assignedDiscountCode: 'RECOVER10',
  },
];

export const INITIAL_RECOVERY_TEMPLATES: RecoveryTemplate[] = [
  {
    channel: 'WHATSAPP',
    headerText: '✨ Aura Skincare Co. Order Update',
    bodyText: 'Hey {{first_name}}! 🌿 We saved your bag with {{cart_items}} (₹{{amount}}). Use code {{discount_code}} for {{discount_percent}}% off in the next 24 hours!',
    buttonText: 'Complete Order (10% Off) 👉',
  },
  {
    channel: 'SMS',
    headerText: 'Aura Skincare',
    bodyText: 'Hey {{first_name}}, your Aura bag is waiting! Take {{discount_percent}}% off with code {{discount_code}}: {{discount_link}}',
    buttonText: 'Shop Now',
  },
  {
    channel: 'EMAIL',
    headerText: 'You left something glowing behind...',
    bodyText: 'Hi {{first_name}},\n\nYour selected skincare items ({{cart_items}}) are waiting for you.\n\nEnjoy an exclusive {{discount_percent}}% off with voucher {{discount_code}}.',
    buttonText: 'Claim Your Order',
  },
];

export const INITIAL_BUSINESS_MEMORIES: BusinessMemory[] = [
  {
    id: 'mem_01',
    organizationId: 'org_aura_skincare',
    concept: 'WhatsApp Recovery Timing',
    insightText: 'Cart recovery messages sent 45–90 minutes post-abandonment have a 34% conversion rate vs 9% at 24 hours.',
    confidence: 0.96,
    category: 'CART_RECOVERY',
    impactMetric: '34% Conversion',
    createdAt: '2026-08-10T14:20:00Z',
  },
  {
    id: 'mem_02',
    organizationId: 'org_aura_skincare',
    concept: 'Dermatologist UGC Scalability',
    insightText: 'Video hooks with medical credibility outperform founder story ads by 3.2x on cold audiences.',
    confidence: 0.94,
    category: 'CREATIVE_FATIGUE',
    impactMetric: '3.2x ROAS multiple',
    createdAt: '2026-08-12T09:15:00Z',
  },
  {
    id: 'mem_03',
    organizationId: 'org_aura_skincare',
    concept: 'Weekend ROAS Decay',
    insightText: 'Saturday evening ad spend generates 22% higher CPA. Cap weekend budget increases at +15%.',
    confidence: 0.91,
    category: 'BUDGET_SCALING',
    impactMetric: '22% CPA saving',
    createdAt: '2026-08-14T18:00:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log_01',
    organizationId: 'org_aura_skincare',
    actionId: 'act_meta_pause_reallocate',
    actionName: 'Paused Fatigued Adset Summer_Set_B & Shifted Budget',
    actor: 'USER',
    timestamp: '2026-08-19T06:15:00Z',
    metadata: { adsetId: 'adset_summer_B', savedBudget: 24000 },
  },
];

export const INITIAL_CHAT_HISTORY: ChatMessage[] = [
  {
    id: 'msg_welcome',
    sender: 'assistant',
    text: `👋 Hello! I am **Operator AI v4.0**, your autonomous operating system for **Aura Skincare Co.**

I've analyzed your store performance:
- 💰 **Yesterday Sales:** ₹3,42,800 (31% Take-Home Profit)
- 🎯 **Ad Warning:** Meta adset \`Summer_Set_B\` fatigued (Frequency 6.2x).
- 📦 **Inventory Alert:** \`Radiance Glow Serum\` has **6.5 Days of Supply Left**.
- 🛒 **Cart Recovery:** 42 high-intent drops (₹88,400) waiting for automated recovery.

How can I help you grow today?`,
    timestamp: new Date().toISOString(),
  },
];
